debug = true
logLevel = "DEBUG"
defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"

# API definition
[api]
  debug = true
  dashboard = true

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedByDefault = true
swarmMode = false
